#!/bin/bash
PROGNAME=$(basename $0)

if [ $# -eq 0 ]
then
    echo "usage: ${PROGNAME} <wallpaper root dir>"
    exit 1
fi

if [ ! $(command -v feh) ]
then
    echo "${PROGNAME} uses feh. Please install feh before use."
    exit 1
fi

DIR=$1
EXCLUDE="/Girls/" # sue me

NUMWALL=$(xrandr -q | grep connected | grep -v disconnected | wc -l)

# TODO: find a way to shorten??
IMGS=$(find $DIR -type f \( -name '*.jpg'  -o -name '*.jpeg' -o -name '*.png' \) -print | egrep -v $EXCLUDE | shuf -n $NUMWALL | tr "\\n" " ")


feh --bg-fill --no-fehbg ${IMGS}
