#!/bin/bash

PROGNAME=$(basename $0)
CMD=/home/jjin/bin/ranwall
DIR=/home/jjin/Dropbox/Images/Wallpapers

if [ $# -eq 0 ]
then
    echo "usage: ${PROGNAME} <time interval (m)>"
    exit 1
fi

while true; do
    $CMD $DIR
    sleep $1m
done
