#!/bin/bash
PROGNAME=$(basename $0)

REQARGS=1

if [ $# -lt $REQARGS ]
then
    echo "usage: ${PROGNAME} <wallpaper root dir>"
    exit 1
fi

if [ ! $(command -v feh) ]
then
    echo "${PROGNAME} DEPENDENCIES:"
    echo "* feh"
    exit 1
fi

DIR=$1
EXCLUDE="/Girls/" # sue me

NUMWALL=$(xrandr -q | grep connected | grep -v disconnected | wc -l)

# TODO: find a way to shorten??
IMGS=$(find $DIR -type f \( -name '*.jpg'  -o -name '*.jpeg' -o -name '*.png' \) -print | egrep -v $EXCLUDE | shuf -n $NUMWALL | tr "\\n" " ")

# TODO: not taking whitespaces (again...)
feh --bg-fill --no-fehbg ${IMGS}
