#!/bin/bash
PROGNAME=$(basename $0)
if [ ! $(command -v openconnect) ]
then
    echo "${PROGNAME}  DEPENDENCIES:"
    echo "* openconnect"
    exit 1
fi

read -p "Username: " UNAME
read -p "Password: " -s PW
# TODO: print newline after accepting pw

# TODO: *REALLY* bad sudo practice; work it out
echo -n $PW | sudo openconnect --authgroup=CNetID --user=$UNAME cvpn.uchicago.edu
