#!/bin/bash

# TODO: add usage prompt

read -p "Username: " UNAME
read -p "Password: " -s PW
# TODO: print newline after accepting pw

# TODO: *REALLY* bad sudo practice; work it out
echo -n $PW | sudo openconnect --authgroup=CNetID --user=$UNAME cvpn.uchicago.edu
